### ISSUE TITLE
Update registries if they already exist

### ISSUE THREAD

**Issue by omus** [julia-actions/add-julia-registry#18]
While using [`julia-actions/cache`](https://github.com/julia-actions/cache) I encountered a scenario where my CI registry didn't contain the latest version of a released package.

Here's a snippet of my workflow:
```yaml
- uses: julia-actions/cache@v1
   with:
     cache-name: "${{ github.workflow }}-${{ github.job }}-${{ matrix.pkg.name }}-${{ matrix.version }}-${{ matrix.os }}-${{ matrix.arch }}"
     cache-registries: true
     cache-compiled: true
- uses: julia-actions/add-julia-registry@v1
```

I'll outline the series of events I believed that took place:
1. Opened my PR which triggered the above workflow. The added registries were then cached
2. Updated the Project.toml in my PR to require a release of a package which was not yet released during step 1.
3. Pushed change resulted in triggering of the CI workflow which had a cache hit and loaded the cache registries.
4. The `julia-actions/add-julia-registry` sees that the registries are present and effectively does nothing.

I believe the `add-julia-registry` action should update any existing registries to avoid this kind of problem
