### ISSUE TITLE
Why  `julia-actions/add-julia-registry@v1` comes before `julia-actions/setup-julia@v1` action in readme example?

### ISSUE THREAD

**Issue by sairus7** [julia-actions/add-julia-registry#6]
Shouldn't `julia-actions/setup-julia@v1` always be the first julia-related action?

Code from readme.md:
```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/add-julia-registry@v1 
        with:
          key: ${{ secrets.SSH_KEY }}
          registry: MyOrg/MyRegistry
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - uses: julia-actions/julia-runtest@v1
```
