### ISSUE TITLE
Doesn't work with Windows

### ISSUE THREAD

**Issue by bradcarman** [julia-actions/add-julia-registry#7]
It appears the Windows CI computer doesn't have SSH available.

Here is what I see...

```
Run julia-actions/add-julia-registry@v1
C:\Windows\System32\OpenSSH\ssh-agent.exe
unable to start ssh-agent service, error :1058
```

**Comment by bradcarman** [comment]
With some googling I learned that I can add `Set-Service ssh-agent -StartupType Manual` and this did work to get past this error, so I have ...

```
    steps:
      - run: Set-Service ssh-agent -StartupType Manual
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/add-julia-registry@v1
        with:
          key: ${{ secrets.SSH_KEY }}
          registry: <org>/<name>
```

But now I'm getting the error `git@github.com: Permission denied (publickey).`, whereas I didn't with `ubuntu`.  Maybe windows requires still something else to authenticate?

**Comment by tuckermcclure** [comment]
I have been having the same issue. The following appears to get me past it:

```
env:
  JULIA_PKG_USE_CLI_GIT: true
  
jobs:
  test:
    ...
    steps:
      - name: On Windows, add ssh-agent.
        run: Set-Service ssh-agent -StartupType Manual
        if: runner.os == 'Windows'
      - name: On Windows, make Git use the OpenSSH instead of whatever it uses internally.
        run: git config --global core.sshCommand C:\\Windows\\System32\\OpenSSH\\ssh.exe
        if: runner.os == 'Windows'
      - uses: actions/checkout@v2
      - uses: julia-actions/add-julia-registry@v1
        with:
          key: ${{ secrets.MY_SSH_KEY }}
          registry: MyOrg/MyRegistry
```

With this, my job is able to pull my registry and interpret the Registry.toml. _However_, it's still not actually working. Here's the error I see:

```
Error: EPERM: operation not permitted, rename 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp-1668-gMSAQuJ016gD' -> 'C:\julia-packages\registries\[MyRegistry]'
    at Object.renameSync (fs.js:741:3)
    at rename (D:\a\_actions\julia-actions\add-julia-registry\v1\node_modules\fs-extra\lib\move-sync\move-sync.js:38:8)
    at doRename (D:\a\_actions\julia-actions\add-julia-registry\v1\node_modules\fs-extra\lib\move-sync\move-sync.js:33:10)
    at Object.moveSync (D:\a\_actions\julia-actions\add-julia-registry\v1\node_modules\fs-extra\lib\move-sync\move-sync.js:17:10)
    at cloneRegistry (D:\a\_actions\julia-actions\add-julia-registry\v1\main.js:48:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (D:\a\_actions\julia-actions\add-julia-registry\v1\main.js:64:3) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp-1668-gMSAQuJ016gD',
  dest: 'C:\\julia-packages\\registries\\[MyRegistry]'
}
```
